import React from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
} from "react-native";
import { styles } from "./LearnTopic.styles";
import { Theme } from "@/theme/Theme";
import { Module } from "@/types/Module";
import { ModuleCard } from "./components/ModuleCard";
import { flex } from "@/theme/ThemeUtils";

// Icon component placeholder - replace with your actual icon component
const Icon = ({
  name,
  size = 24,
  color = Theme.colors.text.primary,
  filled = false,
}: {
  name: string;
  size?: number;
  color?: string;
  filled?: boolean;
}) => <View style={{ width: size, height: size }} />;

export const LearnTopicScreen: React.FC = () => {
  const modules: Module[] = [
    {
      id: "1",
      title: "Intro to Stack & Heap",
      description:
        "Understand how data is stored and the speed implications of memory allocation.",
      status: "completed",
    },
    {
      id: "2",
      title: "Ownership Basics",
      description:
        "Learn how Rust manages memory through a system of rules that the compiler checks at compile time.",
      status: "active",
      progress: 45,
    },
    {
      id: "3",
      title: "Borrowing Rules",
      description:
        "Master the concept of references and how they allow multiple access points without data races.",
      status: "locked",
    },
    {
      id: "4",
      title: "Lifetimes & Scopes",
      description:
        "Deep dive into how the compiler validates reference longevity across function boundaries.",
      status: "locked",
    },
  ];

  const pathName = "Rust Systems Architecture";
  const overallProgress = 45;
  const completedModules = 2;
  const totalModules = 5;

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.contentContainer}
      showsVerticalScrollIndicator={false}
    >
      {/* Overall Progress Section */}
      <View style={styles.progressSection}>
        <View style={[flex.rowBetween, { marginBottom: Theme.spacing.md }]}>
          <View
            style={{ flex: 1, maxWidth: "70%", marginRight: Theme.spacing.md }}
          >
            <Text style={styles.progressLabel}>CURRENT PATH</Text>
            <Text style={styles.progressTitle}>{pathName}</Text>
          </View>
          <Text style={styles.progressPercentage}>{overallProgress}%</Text>
        </View>
        <View style={styles.progressBarContainer}>
          <View
            style={[styles.progressBarFill, { width: `${overallProgress}%` }]}
          />
        </View>

        <Text style={styles.progressSubtext}>
          {completedModules} of {totalModules} modules completed
        </Text>
      </View>

      {/* Timeline */}
      <View style={styles.timeline}>
        {modules.map((module, index) => (
          <ModuleCard
            key={module.id}
            module={module}
            isLast={index === modules.length - 1}
            onPress={() => console.log(`Module ${module.id} pressed`)}
          />
        ))}
      </View>

      {/* AI Assessment Teaser */}
      <View style={styles.aiAssessmentCard}>
        <View style={styles.aiIconContainer}>
          <Icon
            name="psychology"
            size={60}
            color={Theme.colors.accent.tealLight}
          />
        </View>

        <View style={styles.aiContent}>
          <Text style={styles.aiTitle}>AI Mastery Check</Text>
          <Text style={styles.aiDescription}>
            Complete "Ownership Basics" to unlock a personalized technical
            assessment generated by Skill Issue AI.
          </Text>

          <View style={styles.aiProgressBars}>
            <View style={styles.aiProgressBarActive}>
              <View style={styles.aiProgressBarFillActive} />
            </View>
            <View style={styles.aiProgressBarInactive} />
            <View style={styles.aiProgressBarInactive} />
          </View>
        </View>
      </View>
    </ScrollView>
  );
};
